apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
    version: "latest"
  name: frontend-latest
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
        api: external        
    spec:
      containers:
      - image: matthiasholzer/udacity-frontend:latest
        name: frontend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always

