version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: matthiasholzer/reverseproxy:latest
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: matthiasholzer/udacity-restapi-user:latest
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: matthiasholzer/udacity-restapi-feed:latest
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: matthiasholzer/udacity-frontend:latest
